### PR TITLE
debian directory moved to top directory

### PR DESCRIPTION
**Pull request by smoe**
Hello,

This PR moves the debian directory to the top level of the source tree where the typical build tools would be looking for it. Changed only a single line in d/rules for that and the application installed with that package starts just fine on my end.

I would very much like to see that package redistributed alongside LinuxCNC in Debian. Is anything speaking against an upload from your side?

Best,
Steffen <moeller@debian.org>

### CODE REVIEW

**Comment by jethornton** [comment]
Hi Setffen,

Where does the .deb end up with this PR?

I have no objection to this ending up in Debian in fact I'm thrilled! Is the license OK?

FYI, I'm doing a complete rework of the tool with the main objective of a 800x600 screen minimum size and many improvements to the GUI side. I just started the other day so not much to look at.
https://github.com/jethornton/mesact2

Thanks
JT

**Comment by smoe** [comment]
Yes, it would be Debian proper (and Ubuntu, ...).  The package likely lands in the non-free section since the firmwares are not built with tools shipping with Debian, yet. Actually, a file
debian/README.source would typically be used to explain how those firmware files came to be. You have raised the idea to have the firmwares remotely somewhere, how about offering them in a separate package so those could be shared?

Other than the firmware I have not see anything suspicious. The MIT ("expact") license is just fine.

**Comment by jethornton** [comment]
When I build the deb as usual with debuild -us -uc I now get errors about copyright
```
Now running lintian mesact_1.1.2_amd64.changes ...
E: mesact source: source-ships-excluded-file mesact_1.1.2_amd64.deb [debian/copyright:5]
E: mesact source: source-ships-excluded-file mesact_1.1.2_arm64.deb [debian/copyright:5]
E: mesact source: source-ships-excluded-file mesact_1.1.2_armhf.deb [debian/copyright:5]
W: mesact source: debian-watch-file-in-native-package [debian/watch]
W: mesact source: missing-license-paragraph-in-dep5-copyright expat [debian/copyright:36]
Finished running lintian.
```

JT

**Comment by smoe** [comment]
The package is fully functional - just lintian making some noise. The .debs in the source tree should not be in the source tree, but they are. A better place would be next to the release tarball or on a github pages accompanying the tool or .. somewhere else. When running uscan to auto-fetch a new version, the .deb files are auto-removed (which is declared in debian/copyright, which is why lintian new that those files should not be there).
The package should not be native since this is no piece of the Debian-infrastructure.

Would you be happy to become the maintainer of that package in Debian? I would then just go ahead and sponsor your package.

**Comment by jethornton** [comment]
I have resolved the complaints from lintian.
Yes, I'm happy to be the maintainer of mesact.

JT

**Pull request merged**
